# Generated by Django 3.2.6 on 2021-08-26 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='condtion',
            name='req_documents',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Requirements Document'),
            preserve_default=False,
        ),
    ]
