# Generated by Django 3.2.6 on 2021-08-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default=1, upload_to='cars/'),
            preserve_default=False,
        ),
    ]
