# Generated by Django 3.2.6 on 2021-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210827_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='child_seat',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
